name: vs_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - pandas

  - openbabel
  - rdkit
  - openmm
  - pdbfixer

  - openff-toolkit
  - openmmforcefields
  - ambertools
  - openff-forcefields

  - smina
  - plip


