name: vistadock_p_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - cudatoolkit=11.8
  - pip=25.3
  - numpy=2.2
  - scipy=1.15
  - pandas=2.3

  - openbabel=3.1
  - rdkit=2025.09
  - openmm=8.2
  - pdbfixer=1.12

  - openff-toolkit=0.16
  - openmmforcefields=0.14
  - ambertools=24.8
  - openff-forcefields=2024.09

  - plip=3.0
  - smina=2017.11


